/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddNewBranch: typeof import('./components/Features/BranchsMangment/AddNewBranch.vue')['default']
    copy: typeof import('./components/sharedAtoms/atoms/FSelect copy.vue')['default']
    DisableReservationsBtn: typeof import('./components/Features/BranchsMangment/DisableReservationsBtn.vue')['default']
    EditBranch: typeof import('./components/Features/BranchsMangment/EditBranch.vue')['default']
    EpCloseBold: typeof import('~icons/ep/close-bold')['default']
    FButton: typeof import('./components/sharedAtoms/atoms/FButton.vue')['default']
    Feature: typeof import('./components/Feature.vue')['default']
    Features: typeof import('./components/Features.vue')['default']
    FHeading: typeof import('./components/sharedAtoms/atoms/FHeading.vue')['default']
    FInput: typeof import('./components/sharedAtoms/atoms/FInput.vue')['default']
    FLoader: typeof import('./components/sharedAtoms/atoms/FLoader.vue')['default']
    FluentMdl2DeactivateOrders: typeof import('~icons/fluent-mdl2/deactivate-orders')['default']
    FModal: typeof import('./components/sharedAtoms/molecules/FModal.vue')['default']
    FSelect: typeof import('./components/sharedAtoms/atoms/FSelect.vue')['default']
    FTable: typeof import('./components/sharedAtoms/molecules/FTable.vue')['default']
    FTimeSlot: typeof import('./components/sharedAtoms/molecules/FTimeSlot.vue')['default']
    FToast: typeof import('./components/sharedAtoms/atoms/FToast.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    IconParkOutlineAdd: typeof import('~icons/icon-park-outline/add')['default']
    Label: typeof import('~icons/la/bel')['default']
    MdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    MdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    Navbar: typeof import('./components/Layout/Navbar.vue')['default']
    RiArrowUpSFill: typeof import('~icons/ri/arrow-up-s-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablerLoader2: typeof import('~icons/tabler/loader2')['default']
    ZondiconsCloseSolid: typeof import('~icons/zondicons/close-solid')['default']
  }
}
